---
- name: Add Unity Hub Beta dnf repo
  become: true
  ansible.builtin.yum_repository:
    name: unityhub-beta
    description: Unity Hub Beta
    baseurl: https://hub.unity3d.com/linux/repos/rpm/unstable
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://hub.unity3d.com/linux/repos/rpm/unstable/repodata/repomd.xml.key
    enabled: true
    file: unityhub_beta

- name: Install Unity Hub
  become: true
  ansible.builtin.dnf:
    name: unityhub
    state: present
