---
- name: Detect Fedora release number
  ansible.builtin.set_fact:
    fedora_release: "{{ ansible_facts['distribution_major_version'] }}"

- name: Install RPM Fusion free + nonfree release packages
  become: true
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_release }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_release }}.noarch.rpm"
    state: present
    disable_gpg_check: true
